user  nginx;
worker_processes  auto;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;


    # 업스트림: 컨테이너 서비스명 사용
    upstream node_upstream { server nodejs:5000; }
    upstream fastapi_upstream { server fastapi:8080; }

    server {
    server_name ubin.world www.ubin.world;

    # Let's Encrypt 인증용 경로
    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /var/www/html;
    }

    # Node.js 리버스 프록시
    location / {
        proxy_pass http://node_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location /garden/ {
        proxy_pass http://node_upstream/garden/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location /garden {
        return 301 /garden/;
    }

    location /unity/ {
        proxy_pass http://fastapi_upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ubin.world/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ubin.world/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


    }
    server {
        if ($host = www.ubin.world) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        if ($host = ubin.world) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        listen 80;
        server_name ubin.world www.ubin.world;
        return 404; # managed by Certbot

    }
    # server {
    #     listen 443 ssl;
    #     server_name ubin.world www.ubin.world;

    #     ssl_certificate /etc/letsencrypt/live/ubin.world/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/ubin.world/privkey.pem;

    #     ssl_protocols TLSv1.2 TLSv1.3;
    #     ssl_ciphers HIGH:!aNULL:!MD5;

    #     location / {
    #         proxy_pass http://localhost:5000;
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection 'upgrade';
    #         proxy_set_header Host $host;
    #         proxy_cache_bypass $http_upgrade;
    #     }
    # }
}
